version: '3'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "9797:80"
    ssh:
        build:
            context: ./ssh
            dockerfile: Dockerfile
        ports:
            - "8822:22"
            
'''ftp:
        build:
            context: ./ftp  # Dockerfile eta konfigurazioaren kokapena
            dockerfile: Dockerfile
        #container_name: ftp-server
        ports:
            - "8821:21"'''